name: list_versions
version: 0.04
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: '"easify" writing Makefile.PL and Build.PL by'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::Script: 1.02
provides:
  list_versions:
    file: list_versions.pl
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
